const API_BASE=window.SHUUD_API_BASE||"/api/v1/shuud";
const CASE_KEY="shuud:lastCase";
const order=["incident","evidence","decision","insurance","escrow","release","clearance"];
const flowEls=[...document.querySelectorAll(".flow-step")];
const checks=["Даатгал хүчинтэй","SHIID APPROVE","Хүний гэмтэлгүй","Гуравдагч этгээдийн хохиролгүй","Маргаангүй","Залилангийн дохиогүй","Нотлох материал бүрэн","Хохирол ≤ ₮2,000,000"];
const checksEl=document.getElementById("checks"),logEl=document.getElementById("log");
checksEl.innerHTML=checks.map(x=>`<div class="check"><span>${x}</span><b class="ok">PASS</b></div>`).join("");
let pollTimer=null;
async function api(path){const r=await fetch(API_BASE+path,{headers:{accept:"application/json"}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(`${r.status}: ${b.detail||r.statusText}`);return b}
function money(v){if(v==null||v==="")return "—";return `₮${Math.round(Number(v)).toLocaleString("mn-MN")}`}
function setFlow(state){let idx=order.indexOf(state);if(state==="complete")idx=order.length;flowEls.forEach((el,i)=>{el.classList.toggle("active",i===idx);el.classList.toggle("done",i<idx)})}
function logEvent(text,status="PASS"){const el=document.createElement("div");el.className="check";el.innerHTML=`<span>${text}</span><b class="ok">${status}</b>`;logEl.prepend(el)}
function render(c){if(!c||!c.incident_id)return;document.getElementById("incidentValue").textContent=c.incident_id;document.getElementById("incidentLabel").textContent=c.incident_id;document.getElementById("decisionValue").textContent=c.decision||"—";document.getElementById("decisionBadge").textContent=c.decision||"WAITING";document.getElementById("decisionBadge").className=`badge ${c.decision==="APPROVE"?"success":""}`;document.getElementById("insuranceValue").textContent=c.insurance?"ХҮЧИНТЭЙ":"ШАЛГАЖ БАЙНА";document.getElementById("providerValue").textContent=c.provider||"NEF";document.getElementById("escrowValue").textContent=c.escrow_id?(c.payment==="RELEASED"?"RELEASED":"LOCKED"):"—";document.getElementById("paymentValue").textContent=c.payment||"—";document.getElementById("damageValue").textContent=money(c.damage_estimate_mnt);document.getElementById("lockedValue").textContent=c.escrow_id?money(c.damage_estimate_mnt):"—";document.getElementById("paymentState").textContent=c.payment||"—";document.getElementById("clearanceValue").textContent=c.clearance_seconds!=null?`${Number(c.clearance_seconds).toFixed(1)} сек`:"—";document.getElementById("savedValue").textContent=c.economic_savings_mnt!=null?money(c.economic_savings_mnt):"—";setFlow(c.state);document.getElementById("systemStatus").textContent=c.state==="complete"?"CASE COMPLETE":"CASE LIVE";logEl.innerHTML="";const labels={incident:"Бүртгэл: кейс бүртгэгдсэн",evidence:"Баталгаажуулалт: баримт, байршил, зөвшөөрөл баталгаажсан",decision:`SHIID: ${c.decision||"—"}`,insurance:c.insurance?"Даатгал: хүчинтэй · эх үүсвэр баталгаажсан":"Даатгал: шалгаж байна",escrow:"Эскроу: эх үүсвэр түгжигдсэн",release:"Төлбөр: RELEASED · баталгаажсан",clearance:`Зам чөлөөлөлт: ${c.clearance_seconds!=null?Number(c.clearance_seconds).toFixed(1)+" сек":"хүлээгдэж байна"}`};const count=c.state==="complete"?order.length:Math.max(0,order.indexOf(c.state)+1);order.slice(0,count).forEach(k=>logEvent(labels[k]));if(c.state==="complete")logEvent(`Эдийн засгийн үр нөлөө: ${money(c.economic_savings_mnt)} хэмнэлт`)}
async function refresh(id){try{const c=await api(`/incidents/${encodeURIComponent(id)}`);render(c);return c}catch(e){console.warn("SHUUD insurer refresh failed",e);return null}}
function stop(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}}
async function load(){let saved=null;try{saved=JSON.parse(localStorage.getItem(CASE_KEY)||"null")}catch(_){}const q=new URLSearchParams(location.search).get("incident_id");const id=q||(saved&&saved.incident_id);if(!id){document.getElementById("systemStatus").textContent="CASE WAITING";return}await refresh(id);stop();pollTimer=setInterval(()=>refresh(id),2000)}
window.addEventListener("storage",e=>{if(e.key===CASE_KEY&&e.newValue)try{const c=JSON.parse(e.newValue);if(c&&c.incident_id)refresh(c.incident_id)}catch(_){}});
load();